import json
import urllib.request
import uuid

# Configuration
NEO4J_URL = "http://localhost:7474/db/neo4j/tx/commit"
NEO4J_AUTH = ("neo4j", "stolink123")
PROJECT_ID = "6e686700-34cf-4b23-ae2d-f673743dc4ce"
OUTPUT_FILE = "les_mis_vol1_finale_export.cypher"

def run_cypher(statement, params={}):
    payload = {
        "statements": [{
            "statement": statement,
            "parameters": params
        }]
    }
    data = json.dumps(payload).encode("utf-8")

    # Create password manager
    password_mgr = urllib.request.HTTPPasswordMgrWithDefaultRealm()
    password_mgr.add_password(None, NEO4J_URL, NEO4J_AUTH[0], NEO4J_AUTH[1])
    handler = urllib.request.HTTPBasicAuthHandler(password_mgr)
    opener = urllib.request.build_opener(handler)

    req = urllib.request.Request(NEO4J_URL, data=data, headers={"Content-Type": "application/json"})

    try:
        with opener.open(req) as response:
            result = json.loads(response.read().decode("utf-8"))
            if result.get("errors"):
                print(f"Error executing Cypher: {result['errors']}")
                return None
            return result
    except Exception as e:
        print(f"HTTP Error: {e}")
        return None

def format_prop(value):
    if isinstance(value, str):
        # Escape single quotes and backslashes
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    elif value is None:
        return "null"
    elif isinstance(value, bool):
        return "true" if value else "false"
    else:
        return str(value)

def generate_export():
    print(f"Exporting data for project {PROJECT_ID}...")

    cypher_lines = []
    cypher_lines.append(f"// Export for Project: {PROJECT_ID}")
    cypher_lines.append(f"// Generated by StoLink Backend Agent")
    cypher_lines.append("")

    # 1. Fetch Nodes
    # We match all nodes with the projectId property.
    query_nodes = """
    MATCH (n)
    WHERE n.projectId = $projectId
    RETURN labels(n) as labels, properties(n) as props
    """
    result_nodes = run_cypher(query_nodes, {"projectId": PROJECT_ID})

    if not result_nodes:
        print("Failed to fetch nodes.")
        return

    nodes = []
    for row in result_nodes["results"][0]["data"]:
        labels = row["row"][0]
        props = row["row"][1]

        # Exclude embeddingJson
        if "embeddingJson" in props:
            del props["embeddingJson"]

        nodes.append({"labels": labels, "props": props})

    print(f"Found {len(nodes)} nodes.")

    # Generate Node Merge Statements
    for node in nodes:
        labels_str = ":" + ":".join(node["labels"])
        props = node["props"]

        # Assume 'id' is the primary key for MERGE if it exists, otherwise use fallback
        node_id = props.get("id")

        if node_id:
            # MERGE (n:Label {id: '...'})
            prop_str = f"id: {format_prop(node_id)}"
            set_props = []
            for k, v in props.items():
                if k != "id":
                    set_props.append(f"n.{k} = {format_prop(v)}")

            line = f"MERGE (n{labels_str} {{ {prop_str} }})"
            if set_props:
                line += f" SET {', '.join(set_props)}"
            cypher_lines.append(line)
        else:
            # If no ID, use all properties for MERGE (risky if duplicates) or just CREATE
            # Using CREATE for safety if no ID found, but might duplicate.
            prop_list = [f"{k}: {format_prop(v)}" for k, v in props.items()]
            prop_str = ", ".join(prop_list)
            cypher_lines.append(f"CREATE (:{labels_str} {{ {prop_str} }})")

    cypher_lines.append("")

    # 2. Fetch Relationships
    # MATCH (a)-[r]->(b) WHERE a.projectId = ... AND b.projectId = ...
    query_rels = """
    MATCH (a)-[r]->(b)
    WHERE a.projectId = $projectId AND b.projectId = $projectId
    RETURN a.id as startId, type(r) as type, properties(r) as props, b.id as endId, labels(a) as startLabels, labels(b) as endLabels
    """
    result_rels = run_cypher(query_rels, {"projectId": PROJECT_ID})

    if result_rels:
        rels = []
        for row in result_rels["results"][0]["data"]:
            start_id = row["row"][0]
            rel_type = row["row"][1]
            rel_props = row["row"][2]
            end_id = row["row"][3]
            start_labels = row["row"][4] # List of labels
            end_labels = row["row"][5]   # List of labels

            if start_id and end_id:
                rels.append({
                    "start": start_id,
                    "end": end_id,
                    "type": rel_type,
                    "props": rel_props,
                    "startLabel": start_labels[0] if start_labels else "Node", # Use first label for matching optimization
                    "endLabel": end_labels[0] if end_labels else "Node"
                })

        print(f"Found {len(rels)} relationships.")

        for rel in rels:
            # MATCH (a:Label {id: ...}), (b:Label {id: ...}) MERGE (a)-[r:TYPE]->(b)
            start_match = f"(a:{rel['startLabel']} {{id: {format_prop(rel['start'])}}})"
            end_match = f"(b:{rel['endLabel']} {{id: {format_prop(rel['end'])}}})"

            rel_props_str = ""
            if rel["props"]:
                props_list = [f"{k}: {format_prop(v)}" for k, v in rel["props"].items()]
                rel_props_str = f" {{ {', '.join(props_list)} }}"

            line = f"MATCH {start_match} MATCH {end_match} MERGE (a)-[:{rel['type']}{rel_props_str}]->(b)"
            cypher_lines.append(line)

    cypher_lines.append("")

    # Write to file
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(cypher_lines))

    print(f"Successfully generated {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_export()
