package com.stolink.backend.domain.event.service;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.stolink.backend.domain.character.node.Character;
import com.stolink.backend.domain.character.repository.CharacterRepository;
import com.stolink.backend.domain.event.dto.EventResponse;
import com.stolink.backend.domain.event.node.Event;
import com.stolink.backend.domain.event.repository.EventNeo4jRepository;
import com.stolink.backend.domain.project.entity.Project;
import com.stolink.backend.domain.project.repository.ProjectRepository;
import com.stolink.backend.domain.user.entity.User;
import com.stolink.backend.domain.user.repository.UserRepository;
import com.stolink.backend.global.common.exception.ResourceNotFoundException;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

/**
 * 이벤트 조회 서비스 (Neo4j 기반)
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EventService {

    private final EventNeo4jRepository eventNeo4jRepository;
    private final CharacterRepository characterRepository; // Neo4j Repository
    private final ProjectRepository projectRepository;
    private final UserRepository userRepository;

    /**
     * 캐릭터가 참여한 이벤트 목록 조회
     */
    public List<EventResponse> getEventsByCharacter(UUID userId, UUID characterId) {
        log.info("Fetching events for characterId: {}, userId: {}", characterId, userId);

        // 1. Neo4j에서 캐릭터 조회
        Character character = characterRepository.findById(characterId.toString())
                .orElseThrow(() -> {
                    log.error("Character not found in Neo4j: {}", characterId);
                    return new ResourceNotFoundException("Character not found: " + characterId);
                });

        // 2. 프로젝트 조회 및 소유권 검증
        UUID projectId;
        try {
            projectId = UUID.fromString(character.getProjectId());
        } catch (IllegalArgumentException e) {
            throw new ResourceNotFoundException("Invalid Project ID in Character node");
        }

        Project project = projectRepository.findByIdWithUser(projectId)
                .orElseThrow(() -> {
                    log.error("Project not found: {}", projectId);
                    return new ResourceNotFoundException("Project not found: " + projectId);
                });

        if (!project.getUser().getId().equals(userId)) {
            log.error("Project access denied. Project Owner: {}, Requester: {}", project.getUser().getId(), userId);
            throw new ResourceNotFoundException("Project not found");
        }

        // 3. 필터링 (Neo4j에서 가져온 후 메모리 필터링)
        String characterName = character.getName();
        List<Event> events = eventNeo4jRepository.findByProjectId(projectId.toString());

        log.info("Found {} events for project {}, filtering by character '{}'",
                events.size(), projectId, characterName);

        return events.stream()
                .filter(event -> event.getParticipants() != null && event.getParticipants().contains(characterName))
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    /**
     * 프로젝트의 전체 이벤트 목록 조회
     */
    @Transactional(readOnly = true)
    public List<EventResponse> getEventsByProject(UUID userId, UUID projectId) {
        User user = getUserOrThrow(userId);
        getProjectOrThrow(projectId, user);

        List<Event> events = eventNeo4jRepository.findByProjectId(projectId.toString());
        return events.stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    private EventResponse toResponse(Event node) {
        // Node ID is String, DTO expects UUID. If Node ID is not UUID format, generate
        // one or handle error.
        // Assuming Node ID generated by UUIDStringGenerator is a valid UUID string.
        UUID id = null;
        try {
            if (node.getId() != null) {
                id = UUID.fromString(node.getId());
            }
        } catch (IllegalArgumentException e) {
            // If ID is not UUID, leave null or generate random (though persistent ID
            // preferred)
            log.warn("Node ID is not UUID format: {}", node.getId());
        }

        UUID documentId = null;
        try {
            if (node.getDocumentId() != null) {
                documentId = UUID.fromString(node.getDocumentId());
            }
        } catch (IllegalArgumentException e) {
            log.warn("Document ID in node is not UUID format: {}", node.getDocumentId());
        }

        UUID projectId = null;
        try {
            if (node.getProjectId() != null) {
                projectId = UUID.fromString(node.getProjectId());
            }
        } catch (IllegalArgumentException e) {
            log.warn("Project ID in node is not UUID format: {}", node.getProjectId());
        }

        return new EventResponse(
                id,
                node.getEventId(),
                node.getNarrativeSummary(), // Name maps to NarrativeSummary or generic name if available
                node.getEventType(),
                node.getDescription(),
                node.getParticipants(),
                node.getChapter(),
                node.getSequenceOrder(),
                node.getNarrativeSummary(),
                node.getImportance() != null ? node.getImportance().doubleValue() : null,
                node.getLocationRef(),
                null, // StartTime
                null, // EndTime
                documentId,
                projectId);
    }

    private User getUserOrThrow(UUID userId) {
        return userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found: " + userId));
    }

    private void getProjectOrThrow(UUID projectId, User user) {
        projectRepository.findByIdAndUser(projectId, user)
                .orElseThrow(() -> new ResourceNotFoundException("Project not found: " + projectId));
    }
}
